name: Zap Full Scan

on:
  schedule:
    # 1900 hrs Sunday (UTC)
    - cron: "0 19 * * 0"
  workflow_dispatch:

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://juice-shop.herokuapp.com/#/'
          rules_file_name: '.zap/rules.tsv'

